// Scene names start here
export const SCENE_PRELOAD_ASSETS = "PreloadAssetsScene";
export const SCENE_LOADING = "LoadingScene";
export const SCENE_START_SCREEN = "StartScene";
export const SCENE_REGISTER = "RegisterScene";
export const SCENE_LOGIN = "LoginScene";
export const SCENE_LOGIN_SHARED_DEVICE = "LoginSharedDevicePromptScene";
export const SCENE_LOGIN_SHARED_PASSWORD = "LoginSavePasswordPromptScene";
export const SCENE_ERROR = "ErrorScene";
export const SCENE_SERVER_SELECTION = "ServerSelectionScene";
export const SCENE_ROOM_TOWN = "TownScene";
export const SCENE_MAP = "MapScene";
// Scene names end here